In [1]:
import math

In [4]:
from math import *

In [5]:
sqrt(3)

1.7320508075688772

In [6]:
import yfinance as yf
ticker = "IBM"
data = yf.download(ticker, start="2024-06-06", end="2024-10-10")

[*********************100%***********************]  1 of 1 completed


In [8]:
type(data)

pandas.core.frame.DataFrame

In [10]:
data.to_csv('./IBM-2024-6_10')

In [3]:
sqrt(3)

3.142857142857143

In [15]:
import numpy as np
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.identity(4
            )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a=np.array([[1,2,3],[4,5,6]],float)
b=np.array([[1,2],[3,3],[4,5]],float)	
np.dot(a,b)

array([[19., 23.],
       [43., 53.]])

In [24]:
import scipy as sp
from scipy import stats
ret=np.array([0.1,0.05,-0.02])
stp =stats.tmean(ret)
print(stp)

0.04333333333333334


### perpetuity
a bond or other security with no fixed maturity date.

 For	a	perpetuity,	the	same	cash	flow	happens	at	the	same	interval	forever.	A
 growing	perpetuity	is	defined	as	follows:	the	future	cash	flow	is	increased	at
 a	constant	growth	rate	forever.	If	the	first	cash	flow	happens	at	the	end	of
 the	first	period,

Insurance policies are not perpetuities because they often have a defined end date or are contingent on specific events. However, some insurance-like products, such as annuities, could provide ongoing payments for a long duration, but still not truly for perpetuity.